"""HTTP routes and GUI tools documented next to the Click command tree."""

from __future__ import annotations

from typing import Any, Dict, List

HTTP_ROUTES: List[Dict[str, Any]] = [
    {
        "id": "root",
        "method": "GET",
        "path": "/",
        "summary": "HTML GUI index, or JSON lookup of the TCP peer.",
        "query": [],
        "cli": "looking-glass ip <peer>",
        "accept": "HTML if Accept prefers text/html; JSON otherwise.",
        "notes": "JSON uses classify_query on the visitor address.",
    },
    {
        "id": "token",
        "method": "GET",
        "path": "/<token>",
        "summary": "Auto-detect IP, ASN (AS13335), or ISO country (AU).",
        "query": [],
        "cli": "looking-glass ip <token>",
        "accept": "JSON or HTML report.",
        "notes": "classify_query: ipaddress, then ASN digits, then canonical_country.",
    },
    {
        "id": "dns",
        "method": "GET",
        "path": "/dns/<name>",
        "summary": "DNS lookup. Optional /<type> (A, AAAA, MX, DS, …).",
        "query": ["server=<ip>", "port=<1-65535>"],
        "cli": "looking-glass dns [@server] <name> [type]",
        "accept": "JSON or HTML report.",
        "notes": "normalize_qname + canonicalize_qtype. ?server= is an IP only. CLI --timeout is not an HTTP query param.",
    },
    {
        "id": "reputation",
        "method": "GET",
        "path": "/reputation/<name>",
        "summary": "DNSBL / domain lists, plus Sender Score.",
        "query": [],
        "cli": "looking-glass reputation <name>",
        "accept": "JSON or HTML report.",
        "notes": "IP via ipaddress; otherwise normalize_qname.",
    },
    {
        "id": "apex",
        "method": "GET",
        "path": "/apex/<domain>",
        "summary": "Zone and mail health (Apex report).",
        "query": [],
        "cli": "looking-glass apex <domain>",
        "accept": "JSON or HTML report.",
        "notes": "Rejects a bare IP; normalize_qname.",
    },
    {
        "id": "register",
        "method": "GET",
        "path": "/register/<name>",
        "summary": "DNS-delegation chessboard of a label across every IANA TLD.",
        "query": ["tlds=com,net"],
        "cli": "looking-glass register <name> [--tlds com,net]",
        "accept": "JSON or HTML report.",
        "notes": "example.com keeps the first label. NXDOMAIN is no-dns; NS is has-ns; NODATA/wildcard/RDAP-registered is unknown. Not a registrar cart. Rejects a bare IP.",
    },
    {
        "id": "dnssec",
        "method": "GET",
        "path": "/dnssec/<domain>",
        "summary": "Walk DS/DNSKEY from the IANA root anchors.",
        "query": [],
        "cli": "looking-glass dnssec <domain>",
        "accept": "JSON or HTML report.",
        "notes": "Rejects a bare IP; normalize_qname.",
    },
    {
        "id": "tls",
        "method": "GET",
        "path": "/tls/<host>",
        "summary": "TLS handshake and certificate. Optional /<port> (default 443).",
        "query": ["sni=<hostname>"],
        "cli": "looking-glass tls <host> [-p port] [--sni name]",
        "accept": "JSON or HTML report.",
        "notes": "Port 1–65535. ?sni= is stripped only.",
    },
    {
        "id": "rdap",
        "method": "GET",
        "path": "/rdap/<token>",
        "summary": "RDAP for an IP, domain, or ASN.",
        "query": [],
        "cli": "looking-glass rdap <token>",
        "accept": "JSON or HTML report.",
        "notes": "Path rest is mostly pass-through (quoted into rdap.org).",
    },
    {
        "id": "whois",
        "method": "GET",
        "path": "/whois/<token>",
        "summary": "RDAP by default; legacy port-43 WHOIS with ?legacy=1.",
        "query": ["legacy=1|true|yes|legacy|whois"],
        "cli": "looking-glass whois <token> [--legacy]",
        "accept": "JSON or HTML report.",
        "notes": "Domain/IP tokens are not normalized in _plan.",
    },
    {
        "id": "bgp",
        "method": "GET",
        "path": "/bgp/<ip-or-prefix>",
        "summary": "RIPEstat origin ASN and RPKI.",
        "query": [],
        "cli": "looking-glass bgp <ip-or-prefix>",
        "accept": "JSON or HTML report.",
        "notes": "ipaddress.ip_network / ip_address.",
    },
    {
        "id": "dnstrace",
        "method": "GET",
        "path": "/dnstrace/<name>",
        "summary": "Iterative walk from the IANA root. Optional /<type>.",
        "query": [],
        "cli": "looking-glass dnstrace <name> [-t type]",
        "accept": "JSON or HTML report.",
        "notes": "_plan does not run normalize_qname / canonicalize_qtype.",
    },
    {
        "id": "http",
        "method": "GET",
        "path": "/http/<host-or-url>",
        "summary": "Follow redirects; headers, HTTP version, TTFB.",
        "query": ["scheme=http|https"],
        "cli": "looking-glass http <host-or-url>",
        "accept": "JSON or HTML report.",
        "notes": "Connects to the named host (open lookup / SSRF if the server can reach private nets).",
    },
    {
        "id": "ptr",
        "method": "GET",
        "path": "/ptr/<ip>",
        "summary": "PTR plus forward-confirmed reverse DNS.",
        "query": [],
        "cli": "looking-glass ptr <ip>",
        "accept": "JSON or HTML report.",
        "notes": "Requires a valid IP.",
    },
    {
        "id": "mail",
        "method": "GET",
        "path": "/mail/<domain>",
        "summary": "MX/SPF/DMARC/DKIM, SMTP banner and STARTTLS.",
        "query": [],
        "cli": "looking-glass mail <domain>",
        "accept": "JSON or HTML report.",
        "notes": "normalize_qname inside the mail checker.",
    },
    {
        "id": "tcp",
        "method": "GET",
        "path": "/tcp/<host>/<port>",
        "summary": "TCP connect and a short banner.",
        "query": [],
        "cli": "looking-glass tcp <host> -p <port>",
        "accept": "JSON or HTML report.",
        "notes": "Port range checked; host is not normalized in _plan.",
    },
    {
        "id": "pmtu",
        "method": "GET",
        "path": "/pmtu/<host>",
        "summary": "Path MTU via don't-fragment ping payloads.",
        "query": [],
        "cli": "looking-glass pmtu <host>",
        "accept": "JSON or HTML report.",
        "notes": "subprocess argv list (no shell); target is still user-controlled.",
    },
    {
        "id": "ping",
        "method": "GET",
        "path": "/ping/<host>",
        "summary": "ICMP echo (TCP 443 fallback if ICMP is filtered).",
        "query": [],
        "cli": "looking-glass ping <host>",
        "accept": "JSON or HTML report.",
        "notes": "IP or normalize_qname. Python sockets, no shell.",
    },
    {
        "id": "traceroute",
        "method": "GET",
        "path": "/traceroute/<host>",
        "summary": "UDP traceroute, three probes per hop.",
        "query": [],
        "cli": "looking-glass traceroute <host>",
        "accept": "JSON or HTML report.",
        "notes": "IP or normalize_qname.",
    },
    {
        "id": "mtr",
        "method": "GET",
        "path": "/mtr/<host>",
        "summary": "Repeated path, loss and RTT like mtr --report.",
        "query": ["cycles=<n>"],
        "cli": "looking-glass mtr <host> [-c N]",
        "accept": "JSON or HTML report.",
        "notes": "IP or normalize_qname. ?cycles= is mtr -c, default 10, clamped by mtr.max_cycles.",
    },
    {
        "id": "tcptraceroute",
        "method": "GET",
        "path": "/tcptraceroute/<host>",
        "summary": "TCP TTL walk. Optional /<port> (default 443).",
        "query": [],
        "cli": "looking-glass tcptraceroute <host> [-p port]",
        "accept": "JSON or HTML report.",
        "notes": "Port 1–65535; IP or normalize_qname.",
    },
    {
        "id": "status",
        "method": "GET",
        "path": "/status",
        "summary": "Hostname, IPv4 and/or IPv6, clock, uptime, load, WSGI/ASGI.",
        "query": [],
        "cli": None,
        "accept": "Always JSON (Cache-Control: no-store).",
        "notes": "Not GUI-gated. Used by the status bar. `ip` is ipv4 or ipv6; both families are also in ipv4 / ipv6. Logged-in responses add user and serve.running / serve.uptime.",
    },
    {
        "id": "docs",
        "method": "GET",
        "path": "/docs",
        "summary": "This documentation (file written by looking-glass docs).",
        "query": [],
        "cli": "looking-glass docs [PATH]",
        "accept": "text/html. 404 until generated.",
        "notes": "Off by default (docs.enabled). When disabled, GET /docs is 404. Reads ~/.looking-glass/data/docs.html and injects live session chrome. Does not regenerate on GET.",
    },
    {
        "id": "docs-regen",
        "method": "POST",
        "path": "/docs",
        "summary": "Rebuild the documentation file from the catalog.",
        "query": [],
        "cli": "looking-glass docs [PATH]",
        "accept": "JSON.",
        "notes": "401 without a session. Rewrites ~/.looking-glass/data/docs.html.",
    },
    {
        "id": "login",
        "method": "POST",
        "path": "/login",
        "summary": "PAM login. First non-root user bootstraps the allowlist.",
        "query": [],
        "cli": "looking-glass auth users",
        "accept": "JSON. Sets an HttpOnly looking_glass_session cookie (opaque file session, not a JWT).",
        "notes": "Root is never allowed. Body is JSON or form username/password.",
    },
    {
        "id": "logout",
        "method": "POST",
        "path": "/logout",
        "summary": "End the GUI session and clear the cookie.",
        "query": [],
        "cli": "looking-glass auth sessions clear",
        "accept": "JSON.",
        "notes": "Deletes the on-disk session file.",
    },
    {
        "id": "session",
        "method": "GET",
        "path": "/session",
        "summary": "Current admin user, or user: null.",
        "query": [],
        "cli": None,
        "accept": "JSON.",
        "notes": "Public. Does not leak the allowlist. Sessions are 256-bit secrets on disk; the cookie is only the id.",
    },
    {
        "id": "history",
        "method": "GET",
        "path": "/history",
        "summary": "Logged-in global action list. Also /history/<id> for replay JSON or HTML.",
        "query": [],
        "cli": None,
        "accept": "JSON, or HTML for /history/<id>.",
        "notes": "GET /history lists every successful lookup and needs a session. GET /history/<id> is a shareable permalink (JSON or HTML) and does not.",
    },
    {
        "id": "serve-start",
        "method": "POST",
        "path": "/serve/start",
        "summary": "Start the intel server. Also POST /serve/stop.",
        "query": [],
        "cli": "looking-glass lookup-server start|stop",
        "accept": "JSON.",
        "notes": "401 without a session. Status bar shows ready vs building and intel uptime.",
    },
    {
        "id": "cache",
        "method": "GET",
        "path": "/cache",
        "summary": "RDAP/BGP on-disk cache stats. Also /cache/<ns>.",
        "query": [],
        "cli": "looking-glass cache stats [rdap|bgp]",
        "accept": "JSON.",
        "notes": "401 unless a PAM admin session is present.",
    },
    {
        "id": "cache-clear",
        "method": "DELETE",
        "path": "/cache",
        "summary": "Clear cache. Also POST. /cache/<ns> or /cache/<ns>/<file>.",
        "query": [],
        "cli": "looking-glass cache clear [rdap|bgp] [name]",
        "accept": "JSON.",
        "notes": "401 without a session. Filenames use basename; ns in {rdap,bgp}.",
    },
    {
        "id": "config",
        "method": "GET",
        "path": "/config",
        "summary": "Operator config.json. POST sets dotted keys (docs.enabled, locale, cache, refresh, wall, history).",
        "query": [],
        "cli": "looking-glass config [get|set]",
        "accept": "JSON.",
        "notes": "401 without a session. auth.users cannot be set here; use looking-glass auth users.",
    },
    {
        "id": "logs",
        "method": "GET",
        "path": "/logs",
        "summary": "Tail GUI, intel server, wall, and build logs as JSON lines.",
        "query": ["kind", "limit", "ok"],
        "cli": None,
        "accept": "JSON.",
        "notes": "401 without a session. kind=access|error|login|lookup|serve-err|wall|build (serve-out is an alias of lookup). ok=true|false filters login.",
    },
    {
        "id": "logs-stats",
        "method": "GET",
        "path": "/logs/stats",
        "summary": "Per-page hit/error time series for the log viewer charts.",
        "query": [],
        "cli": "looking-glass logs stats",
        "accept": "JSON.",
        "notes": "401 without a session. 15-minute snapshots for the last 24h (day) and 7d (week); stored buckets only, no zero fill.",
    },
]

GUI_TOOLS: List[Dict[str, str]] = [
    {"id": "ip", "label": "IP", "group": "Look up", "form": "form-ip", "path": "/<ip>", "cli": "looking-glass ip"},
    {"id": "asn", "label": "ASN", "group": "Look up", "form": "form-asn", "path": "/AS<number>", "cli": "looking-glass asn"},
    {"id": "bgp", "label": "BGP / RPKI", "group": "Look up", "form": "form-bgp", "path": "/bgp/<ip>", "cli": "looking-glass bgp"},
    {"id": "rdap", "label": "WHOIS", "group": "Look up", "form": "form-rdap", "path": "/rdap/<token>", "cli": "looking-glass rdap / whois --legacy"},
    {"id": "dns", "label": "DNS", "group": "DNS", "form": "form-dns", "path": "/dns/<name>", "cli": "looking-glass dns"},
    {"id": "dnstrace", "label": "DNS trace", "group": "DNS", "form": "form-dnstrace", "path": "/dnstrace/<name>", "cli": "looking-glass dnstrace"},
    {"id": "dnssec", "label": "DNSSEC", "group": "DNS", "form": "form-dnssec", "path": "/dnssec/<domain>", "cli": "looking-glass dnssec"},
    {"id": "apex", "label": "Apex", "group": "DNS", "form": "form-apex", "path": "/apex/<domain>", "cli": "looking-glass apex"},
    {"id": "register", "label": "Register", "group": "DNS", "form": "form-register", "path": "/register/<name>", "cli": "looking-glass register"},
    {"id": "ptr", "label": "PTR", "group": "Look up", "form": "form-ptr", "path": "/ptr/<ip>", "cli": "looking-glass ptr"},
    {"id": "tls", "label": "TLS", "group": "Web", "form": "form-tls", "path": "/tls/<host>[/<port>]", "cli": "looking-glass tls"},
    {"id": "http", "label": "HTTP", "group": "Web", "form": "form-http", "path": "/http/<host>", "cli": "looking-glass http"},
    {"id": "mail", "label": "Mail", "group": "Web", "form": "form-mail", "path": "/mail/<domain>", "cli": "looking-glass mail"},
    {"id": "reputation", "label": "Reputation", "group": "Look up", "form": "form-rep", "path": "/reputation/<name>", "cli": "looking-glass reputation"},
    {"id": "ping", "label": "Ping", "group": "Path", "form": "form-ping", "path": "/ping/<host>", "cli": "looking-glass ping"},
    {"id": "traceroute", "label": "Traceroute", "group": "Path", "form": "form-traceroute", "path": "/traceroute/<host>", "cli": "looking-glass traceroute"},
    {"id": "mtr", "label": "MTR", "group": "Path", "form": "form-mtr", "path": "/mtr/<host>", "cli": "looking-glass mtr"},
    {"id": "tcptraceroute", "label": "TCP traceroute", "group": "Path", "form": "form-tcptraceroute", "path": "/tcptraceroute/<host>[/<port>]", "cli": "looking-glass tcptraceroute"},
    {"id": "tcp", "label": "TCP", "group": "Path", "form": "form-tcp", "path": "/tcp/<host>/<port>", "cli": "looking-glass tcp"},
    {"id": "pmtu", "label": "Path MTU", "group": "Path", "form": "form-pmtu", "path": "/pmtu/<host>", "cli": "looking-glass pmtu"},
]
